name: Deploy website
on:
  push:
    branches:
      - master  # activating push on master branch

jobs:
  test:  # job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

  build:  # job
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build website
        run: npm run build

      - name: publish js file name
        id: publish
        run: |
          echo "script-file=$(find dist/assets/*.js -type f -exec basename {} \;)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json

  deploy:  # job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Output script file name
        run: echo "${{ needs.build.outputs.script-file }}"

      - name: Output contents
        run: ls

      - name: Deploy
        run: echo "Deploying..."  # show dummy message in terminal